# Generated by Django 5.0.6 on 2025-11-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
