# Generated by Django 5.0.6 on 2025-11-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag_cliente_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_whatsapp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='core.tag'),
        ),
    ]
